### ISSUE TITLE
Convert sql field GeofencingLatitude to avro

### ISSUE THREAD

**Issue by hgbink** [woodlee/sqlserver-cdc-to-kafka#17]
Hi, 
Thanks for providing this repo.  I was trying to run it for my sql database and got the following error : 
`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/[REDACTED]/driver/sqlserver-cdc-to-kafka/cdc_kafka/__main__.py", line 4, in <module>
    main.run()
  File "/[REDACTED]/driver/sqlserver-cdc-to-kafka/cdc_kafka/main.py", line 61, in run
    tables: List[tracked_tables.TrackedTable] = build_tracked_tables_from_cdc_metadata(
  File "/[REDACTED]/driver/sqlserver-cdc-to-kafka/cdc_kafka/main.py", line 405, in build_tracked_tables_from_cdc_metadata
    tracked_table.append_field(tracked_tables.TrackedField(
  File "/[REDACTED]/driver/sqlserver-cdc-to-kafka/cdc_kafka/tracked_tables.py", line 26, in __init__
    self.avro_schema: Dict[str, Any] = avro_from_sql.avro_schema_from_sql_type(
  File "/[REDACTED]/driver/sqlserver-cdc-to-kafka/cdc_kafka/avro_from_sql.py", line 82, in avro_schema_from_sql_type
    raise Exception(f"Field '{source_field_name}': I am unsure how to convert SQL type {sql_type_name} to Avro")
Exception: Field 'GeofencingLatitude': I am unsure how to convert SQL type float to Avro`

Any ideas on how to fix it?

**Comment by woodlee** [comment]
Likely fixed in https://github.com/woodlee/sqlserver-cdc-to-kafka/releases/tag/v3.0.0
